defaults:
  - conditioning: ???

_target_: schnetpack_gschnet.ConditionalGenerativeSchNet
representation:
  _target_: schnetpack_gschnet.E3SchNet
  n_atom_basis: 128
  n_interactions: 9
  radial_basis:
    _target_: schnetpack.nn.radial.GaussianRBF
    n_rbf: 25
    cutoff: ${globals.model_cutoff}
  cutoff_fn:
    _target_: schnetpack.nn.cutoff.CosineCutoff
    cutoff: ${globals.model_cutoff}
  max_z: 130
  max_ell: 3
atom_types: ${globals.atom_types}
origin_type: ${globals.origin_type}
focus_type: ${globals.focus_type}
stop_type: ${globals.stop_type}
model_cutoff: ${globals.model_cutoff}
prediction_cutoff: ${globals.prediction_cutoff}
placement_cutoff: ${globals.placement_cutoff}
type_prediction_n_hidden: [206, 156, 106, 56]
distance_prediction_n_hidden: [264, 273, 282, 291]
